version: '3.7'

services:
  labelify_db:
    image: mysql:5.7
    command: mysqld --sql_mode="" --general-log=1 --general-log-file=/var/log/mysql/general-log.log
    container_name: labelify_db
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: a2166128-1279-433c-88de-95bd70444ac3
      MYSQL_USER: usr_labelify
      MYSQL_PASSWORD: 679bbb63-29f8-4f90-b887-417104b6dd1b
      MYSQL_DATABASE: labelify
      TZ: America/Lima
    networks:
      - labelify_network
    healthcheck:
          test: "cat /var/log/mysql/general-log.log | grep \"root@localhost on  using Socket\""
          interval: 1s
          retries: 120

  labelify:
    build: .
    image: labelify
    container_name: labelify
    ports:
     - "80:8080"
    environment:
      LABELIFY_DATABASE_HOST: host.docker.internal
      LABELIFY_DATABASE_USER: usr_labelify
      LABELIFY_DATABASE_PASSWORD: 679bbb63-29f8-4f90-b887-417104b6dd1b
      LABELIFY_DATABASE_NAME: labelify
      LABELIFY_CREATE_TABLES: "true"
      LABELIFY_ADMIN_PASSWORD: 7c30b42c-bb92-4f1d-83d4-ed5acc6f3b5c
      LABELIFY_ANNOTATION_GROUP_IDENTIFIER: e15e3d2f-89fc-4170-9164-592c82f1891f
      TOKEN_SECRET: changeme
      TZ: America/Lima
    networks:
      - labelify_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
        labelify_db:
            condition: service_healthy

networks:
  labelify_network:
    driver: bridge
